"""Format review output as lore-style inline email reply."""

from __future__ import annotations

from kri.common.models import Patch
from kri.llm.models import InlineComment, PatchSummary


def format_lore_reply(
    patch: Patch,
    summary: PatchSummary | None,
    comments: list[InlineComment],
) -> str:
    """Format review as a lore-style email reply with inline comments."""
    parts: list[str] = []

    # Header
    author = patch.author or "the author"
    parts.append(f"On the patch: {patch.subject}")
    parts.append(f"From: {author}")
    parts.append("")

    # Summary
    if summary:
        parts.append(f"This patch {summary.what_it_does}")
        if summary.risk_areas:
            parts.append(f"Risk areas: {', '.join(summary.risk_areas)}")
        parts.append("")

    if not comments:
        parts.append("No significant issues found. Looks good to me.")
        parts.append("")
        parts.append("---")
        parts.append("Generated by KRI (Kernel Review Intelligence) — not a maintainer opinion.")
        return "\n".join(parts)

    # Group comments by file
    by_file: dict[str, list[InlineComment]] = {}
    for c in comments:
        by_file.setdefault(c.file_path, []).append(c)

    # Format inline comments
    diff_lines = patch.diff.split("\n")

    for file_path, file_comments in sorted(by_file.items()):
        parts.append(f"--- {file_path} ---")
        parts.append("")

        for comment in sorted(file_comments, key=lambda c: c.line_number):
            # Find context from diff
            context = _find_context(diff_lines, file_path, comment.line_number)
            if context:
                for ctx_line in context:
                    parts.append(f"> {ctx_line}")
                parts.append("")

            # The review comment
            severity_tag = ""
            if comment.severity.value == "blocker":
                severity_tag = "[BLOCKER] "
            elif comment.severity.value == "warning":
                severity_tag = "[WARNING] "

            parts.append(f"{severity_tag}{comment.message}")

            if comment.suggestion:
                parts.append("")
                parts.append("Suggested fix:")
                for line in comment.suggestion.split("\n"):
                    parts.append(f"  {line}")

            parts.append("")

    # Footer
    parts.append("---")
    n_blockers = sum(1 for c in comments if c.severity.value == "blocker")
    n_warnings = sum(1 for c in comments if c.severity.value == "warning")
    if n_blockers:
        parts.append(f"Summary: {n_blockers} blocker(s), {n_warnings} warning(s) — needs revision.")
    else:
        parts.append(f"Summary: {n_warnings} suggestion(s) — minor issues, otherwise looks good.")
    parts.append("")
    parts.append("---")
    parts.append("Generated by KRI (Kernel Review Intelligence) — not a maintainer opinion.")

    return "\n".join(parts)


def _find_context(
    diff_lines: list[str], file_path: str, target_line: int
) -> list[str]:
    """Extract a few lines of context around the target line from the diff."""
    in_file = False
    new_lineno = 0
    context: list[str] = []

    for line in diff_lines:
        if line.startswith("diff --git"):
            in_file = f"b/{file_path}" in line
            new_lineno = 0
            continue
        if not in_file:
            continue
        if line.startswith("@@"):
            parts = line.split("+")
            if len(parts) >= 2:
                num_part = parts[1].split(",")[0].split(" ")[0]
                try:
                    new_lineno = int(num_part) - 1
                except ValueError:
                    pass
            continue
        if line.startswith("-"):
            continue
        new_lineno += 1
        if abs(new_lineno - target_line) <= 2:
            context.append(line)
        if new_lineno > target_line + 2:
            break

    return context[:5]
