"""Format review output as lore-style inline email reply."""

from __future__ import annotations

from kri.common.models import Patch
from kri.llm.models import InlineComment, PatchSummary
from kri.llm.sanitize import strip_trailers as _strip_trailers


def format_lore_reply(
    patch: Patch,
    summary: PatchSummary | None,
    comments: list[InlineComment],
) -> str:
    """Format review as a lore-style email reply with inline comments.

    Uses upstream_comment (maintainer-voiced text) when available; falls back
    to message. Does not emit [BLOCKER]/[WARNING] prefixes — real lore email
    replies do not use those labels.
    """
    parts: list[str] = []

    # Header
    author = patch.author or "the author"
    parts.append(f"On the patch: {patch.subject}")
    parts.append(f"From: {author}")
    parts.append("")

    # Summary
    if summary:
        parts.append(f"This patch {summary.what_it_does}")
        if summary.risk_areas:
            parts.append(f"Risk areas: {', '.join(summary.risk_areas)}")
        parts.append("")

    if not comments:
        parts.append("No significant issues found. Looks good to me.")
        parts.append("")
        parts.append("---")
        parts.append("Generated by KRI (Kernel Review Intelligence) — not a maintainer opinion.")
        return "\n".join(parts)

    # Group comments by file
    by_file: dict[str, list[InlineComment]] = {}
    for c in comments:
        by_file.setdefault(c.file_path, []).append(c)

    diff_lines = patch.diff.split("\n")

    for file_path, file_comments in sorted(by_file.items()):
        parts.append(f"--- {file_path} ---")
        parts.append("")

        for comment in sorted(file_comments, key=lambda c: c.line_number):
            # Quote context lines with "> " (lore convention)
            context = extract_hunk_context(diff_lines, file_path, comment.line_number)
            if context:
                for ctx_line in context:
                    parts.append(f"> {ctx_line}")
                parts.append("")

            # Use upstream_comment (maintainer-voiced) when available.
            # Strip any trailer lines the LLM may have generated despite instructions.
            body = _strip_trailers(comment.upstream_comment or comment.message)
            if not body:
                body = comment.message.strip()
            parts.append(body)
            parts.append("")

    # Footer
    parts.append("---")
    n_blockers = sum(1 for c in comments if c.severity.value == "blocker")
    n_warnings = sum(1 for c in comments if c.severity.value == "warning")
    if n_blockers:
        parts.append(f"Summary: {n_blockers} concern(s) need addressing before this can be applied.")
    else:
        parts.append(f"Summary: {n_warnings} suggestion(s) — otherwise looks reasonable.")
    parts.append("")
    parts.append("---")
    parts.append("Generated by KRI (Kernel Review Intelligence) — not a maintainer opinion.")

    return "\n".join(parts)


def extract_hunk_context(
    diff_lines: list[str], file_path: str, target_line: int, window: int = 2
) -> list[str]:
    """Extract lines of context around target_line from a unified diff.

    Returns up to (2*window + 1) non-removed lines centered on target_line,
    using only the new-file side. Safe to call with any line number.
    """
    in_file = False
    new_lineno = 0
    context: list[str] = []

    for line in diff_lines:
        if line.startswith("diff --git"):
            in_file = f"b/{file_path}" in line
            new_lineno = 0
            continue
        if not in_file:
            continue
        if line.startswith("@@"):
            parts = line.split("+")
            if len(parts) >= 2:
                num_part = parts[1].split(",")[0].split(" ")[0]
                try:
                    new_lineno = int(num_part) - 1
                except ValueError:
                    pass
            continue
        if line.startswith("-"):
            continue
        new_lineno += 1
        if abs(new_lineno - target_line) <= window:
            context.append(line)
        if new_lineno > target_line + window:
            break

    return context[: 2 * window + 1]
