"""Pydantic models for LLM review output."""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field

from kri.common.models import Severity


class InlineComment(BaseModel):
    """A review comment targeting a specific location in the diff."""

    file_path: str
    line_number: int
    hunk_context: str = ""
    category: str = "general"
    severity: Severity = Severity.INFO
    message: str
    suggestion: str | None = None
    confidence: float = 0.5
    reasoning: str = ""


class PatchSummary(BaseModel):
    """Output of the Summarizer agent."""

    what_it_does: str
    subsystem: str = ""
    components_touched: list[str] = Field(default_factory=list)
    change_type: str = ""
    risk_areas: list[str] = Field(default_factory=list)


class AgentReviewOutput(BaseModel):
    """Standardized output from any review agent."""

    agent_name: str
    patch_id: str
    inline_comments: list[InlineComment] = Field(default_factory=list)
    general_comments: list[str] = Field(default_factory=list)
    confidence: float = 0.5


class IntelligentReport(BaseModel):
    """Full intelligent review output for a patch series."""

    series_id: str
    series_title: str = ""
    disclaimer: str = (
        "SIMULATION DISCLAIMER: This is an AI-generated review from KRI "
        "(Kernel Review Intelligence). It does NOT represent the opinion of "
        "any kernel maintainer. All observations are generated by LLM analysis "
        "and should be verified by a human reviewer before acting upon."
    )
    patches: list[PatchReview] = Field(default_factory=list)
    overall_assessment: str = ""
    lore_reply: str = ""
    rule_based_decisions: list[dict[str, Any]] = Field(default_factory=list)
    metadata: dict[str, Any] = Field(default_factory=dict)


class PatchReview(BaseModel):
    """Review output for a single patch."""

    patch_id: str
    subject: str = ""
    summary: PatchSummary | None = None
    inline_comments: list[InlineComment] = Field(default_factory=list)
    general_comments: list[str] = Field(default_factory=list)
    lore_reply: str = ""
