"""Report Generator (Blueprint Sec. 17 / SPEC §11).

Renders structured Review Explainability Reports from scored Decisions. Every
report carries a mandatory simulation disclaimer (Constitution requirement) and
deterministic output (sorted decisions, fixed epoch timestamps).

The report is a JSON-serializable dict (ReviewReport type) containing: metadata,
summary statistics, per-decision detail (what/why/where + evidence_graph +
confidence breakdown), counterfactuals, and learning references.
"""

from __future__ import annotations

from typing import Any

from kri.common.models import (
    ConfidenceLevel,
    Decision,
    PatchSeries,
    ReasoningLayer,
    Severity,
)

# Type alias for the report dict shape.
ReviewReport = dict[str, Any]

_SIMULATION_DISCLAIMER = (
    "SIMULATION DISCLAIMER: This is a simulated review generated by KRI "
    "(Kernel Review Intelligence). It does NOT represent the opinion of any "
    "kernel maintainer or the Linux community. All observations are derived "
    "from automated static analysis and historical pattern matching only."
)

_FIXED_EPOCH = "2000-01-01T00:00:00Z"


class ReportGenerator:
    """Produces Review Explainability Reports from scored Decisions.

    Reports are deterministic (sorted decisions, fixed timestamp) and carry
    the mandatory simulation disclaimer (Constitution requirement).
    """

    def __init__(self, version: str = "0.1.0") -> None:
        self._version = version

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate(
        self,
        decisions: list[Decision],
        series: PatchSeries | None = None,
    ) -> ReviewReport:
        """Produce the full Review Explainability Report dict.

        Args:
            decisions: Scored Decision objects from the Review Engine.
            series: Optional PatchSeries for metadata enrichment.

        Returns:
            A JSON-serializable dict conforming to the ReviewReport schema.
        """
        sorted_decisions = sorted(decisions, key=lambda d: d.decision_id)

        publishable = [d for d in sorted_decisions if d.is_publishable()]
        unpublishable = [d for d in sorted_decisions if not d.is_publishable()]

        return {
            "disclaimer": _SIMULATION_DISCLAIMER,
            "metadata": {
                "report_version": self._version,
                "generated_at": _FIXED_EPOCH,
                "series_id": series.series_id if series else None,
                "series_title": series.title if series else "",
                "total_decisions": len(decisions),
                "publishable_decisions": len(publishable),
                "unpublishable_decisions": len(unpublishable),
            },
            "summary": self._build_summary(decisions),
            # Constitution Sec. 29/30 ("Unknown is Better Than Wrong"): only
            # publishable decisions may surface as findings.
            "decisions": [self.format_decision(d) for d in publishable],
            "dropped_decisions": [
                self._format_dropped(d) for d in unpublishable
            ],
            "counterfactuals": [],  # placeholder for MVP
            "learning_references": [],  # placeholder for MVP
        }

    @staticmethod
    def _format_dropped(decision: Decision) -> dict[str, Any]:
        """Format a non-publishable Decision for the audit-only drop list.

        Preserves provenance (Constitution Sec. 39) without letting the
        decision surface as a finding."""
        if decision.evidence_graph is None or not decision.evidence_graph.has_verified_evidence():
            reason = "no_verified_evidence"
        elif decision.confidence is None or decision.confidence.level == ConfidenceLevel.UNKNOWN:
            reason = "confidence_unknown"
        else:
            reason = "not_publishable"

        return {
            "decision_id": decision.decision_id,
            "reason": reason,
            "statement": decision.statement,
        }

    def format_decision(self, decision: Decision) -> dict[str, Any]:
        """Format a single Decision into the report dict shape.

        Args:
            decision: A scored Decision object.

        Returns:
            A JSON-serializable dict for this decision entry.
        """
        confidence_dict: dict[str, Any] | None = None
        if decision.confidence is not None:
            confidence_dict = {
                "score": decision.confidence.score,
                "level": decision.confidence.level.value,
                "factors": {
                    f.value: s
                    for f, s in decision.confidence.factor_scores.items()
                },
                "explanation": decision.confidence.explanation,
            }

        evidence_graph_dict: dict[str, Any] | None = None
        if decision.evidence_graph is not None:
            eg = decision.evidence_graph
            rule_dict: dict[str, Any] | None = None
            if eg.subsystem_rule is not None:
                rule_dict = {
                    "rule_id": eg.subsystem_rule.rule_id,
                    "description": eg.subsystem_rule.description,
                    "rule_type": eg.subsystem_rule.rule_type.value,
                }

            evidence_graph_dict = {
                "evidence_count": len(eg.evidence),
                "verified_count": sum(
                    1 for e in eg.evidence if e.verified
                ),
                "items": [
                    {
                        "evidence_id": e.evidence_id,
                        "source_type": e.source_type.value,
                        "summary": e.summary,
                        "verified": e.verified,
                        "strength": e.strength,
                        "source_url": e.provenance.source_url,
                        "repo_path": e.provenance.repo_path,
                    }
                    for e in eg.evidence
                ],
                "rule": rule_dict,
                "accepted_examples": eg.accepted_examples,
                "rejected_examples": eg.rejected_examples,
            }

        # Determine the "why" from the evidence graph rule rationale
        why = ""
        if (
            decision.evidence_graph is not None
            and decision.evidence_graph.subsystem_rule is not None
        ):
            why = decision.evidence_graph.subsystem_rule.rationale

        return {
            "decision_id": decision.decision_id,
            "publishable": decision.is_publishable(),
            "what": decision.statement,
            "why": why,
            "where": decision.location,
            "layer": decision.layer.value,
            "severity": decision.severity.value,
            "category": decision.category,
            "confidence": confidence_dict,
            "evidence_graph": evidence_graph_dict,
        }

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _build_summary(self, decisions: list[Decision]) -> dict[str, Any]:
        """Build the summary statistics section of the report."""
        # Severity counts
        severity_counts: dict[str, int] = {s.value: 0 for s in Severity}
        for d in decisions:
            severity_counts[d.severity.value] += 1

        # Layer counts
        layer_counts: dict[str, int] = {layer.value: 0 for layer in ReasoningLayer}
        for d in decisions:
            layer_counts[d.layer.value] += 1

        # Confidence distribution
        confidence_distribution: dict[str, int] = {
            level.value: 0 for level in ConfidenceLevel
        }
        for d in decisions:
            if d.confidence is not None:
                confidence_distribution[d.confidence.level.value] += 1
            else:
                confidence_distribution[ConfidenceLevel.UNKNOWN.value] += 1

        # Evidence coverage: fraction with verified evidence
        total = len(decisions)
        if total > 0:
            verified_count = sum(
                1
                for d in decisions
                if d.evidence_graph is not None
                and d.evidence_graph.has_verified_evidence()
            )
            evidence_coverage = verified_count / total
        else:
            evidence_coverage = 0.0

        return {
            "severity_counts": severity_counts,
            "layer_counts": layer_counts,
            "confidence_distribution": confidence_distribution,
            "evidence_coverage": evidence_coverage,
        }
